# Generated by Django 2.0.2 on 2018-03-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180301_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.DateField()),
                ('author', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
    ]
