# Generated by Django 2.2.7 on 2019-11-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
