# Generated by Django 3.0.3 on 2020-02-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
