# Generated by Django 3.0.3 on 2020-02-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200216_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='changed',
            field=models.IntegerField(default=0),
        ),
    ]
